export default function TermsOfUse() {
  return (
    <main className="mx-auto max-w-4xl px-4 py-12 md:px-6 md:py-16">
      <article className="prose prose-invert max-w-none">
        <h1 className="text-4xl font-bold tracking-tight text-white">Terms of Use</h1>
        <p className="mt-2 text-slate-400">Last updated: April 5, 2026</p>

        <section className="mt-8 space-y-6">
          <div>
            <h2 className="text-2xl font-semibold text-white">0. What Smart Reply Pro Does</h2>
            <p className="mt-3 text-slate-300">
              Smart Reply Pro is a strategic AI communication workspace. We help you draft, review, and refine replies to incoming messages. Specifically:
            </p>
            <ul className="mt-3 space-y-2 text-slate-300">
              <li className="ml-4 list-disc"><strong>You provide:</strong> Incoming messages and your writing style preferences</li>
              <li className="ml-4 list-disc"><strong>We generate:</strong> AI-suggested replies based on your input</li>
              <li className="ml-4 list-disc"><strong>You decide:</strong> Whether to use, edit, or discard any suggested reply</li>
              <li className="ml-4 list-disc"><strong>We never:</strong> Send, post, or share messages on your behalf</li>
            </ul>
            <p className="mt-4 text-slate-300">
              Smart Reply Pro is not responsible for how you use the replies we generate. You are solely responsible for all messages you send.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white">1. Acceptance of Terms</h2>
            <p className="mt-3 text-slate-300">
              By accessing and using Smart Reply Pro, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white">2. Use License</h2>
            <p className="mt-3 text-slate-300">
              Permission is granted to temporarily download one copy of the materials (information or software) on Smart Reply Pro for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:
            </p>
            <ul className="mt-3 space-y-2 text-slate-300">
              <li className="ml-4 list-disc">Modify or copying the materials</li>
              <li className="ml-4 list-disc">Using the materials for any commercial purpose or for any public display (commercial or non-commercial)</li>
              <li className="ml-4 list-disc">Attempting to decompile or reverse engineer any software contained on Smart Reply Pro</li>
              <li className="ml-4 list-disc">Transferring the materials to another person or &quot;mirroring&quot; the materials on any other server</li>
              <li className="ml-4 list-disc">Removing any copyright or other proprietary notations from the materials</li>
            </ul>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white">3. AI-Generated Content & User Responsibility</h2>
            <p className="mt-3 text-slate-300">
              <strong>AI Output:</strong> All replies suggested by Smart Reply Pro are generated by artificial intelligence. These suggestions are not fact-checked, legally reviewed, or guaranteed to be accurate, appropriate, or suitable for your specific situation.
            </p>
            <p className="mt-3 text-slate-300">
              <strong>Your Responsibility:</strong> You are responsible for:
            </p>
            <ul className="mt-3 space-y-2 text-slate-300">
              <li className="ml-4 list-disc">Reviewing all AI-suggested replies before sending them</li>
              <li className="ml-4 list-disc">Editing, discarding, or customizing suggestions to match your intent and voice</li>
              <li className="ml-4 list-disc">Ensuring that any reply you send complies with all applicable laws and does not violate anyone&apos;s rights</li>
              <li className="ml-4 list-disc">Using the service in good faith and not to harass, defame, threaten, or mislead anyone</li>
            </ul>
            <p className="mt-4 text-slate-300">
              Smart Reply Pro makes no warranty that generated replies will achieve your intended outcome. The AI understands context, tone, and strategy, but it is not a substitute for your own judgment.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white">4. Disclaimer</h2>
            <p className="mt-3 text-slate-300">
              The materials on Smart Reply Pro are provided on an &apos;as is&apos; basis. Smart Reply Pro makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
            </p>
            <p className="mt-3 text-slate-300">
              <strong>Specifically:</strong> Smart Reply Pro does not warrant that any AI-suggested reply will be appropriate, effective, legally compliant, or suitable for any particular purpose. Use the service at your own risk.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white">5. Limitations</h2>
            <p className="mt-3 text-slate-300">
              In no event shall Smart Reply Pro or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on Smart Reply Pro, even if Smart Reply Pro or an authorized representative has been notified orally or in writing of the possibility of such damage.
            </p>
            <p className="mt-3 text-slate-300">
              <strong>Specifically:</strong> Smart Reply Pro is not liable for any negative outcomes, relationship damage, professional consequences, or legal issues resulting from your use of AI-generated replies, even if we have been advised of the possibility of such harm.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white">6. Accuracy of Materials</h2>
            <p className="mt-3 text-slate-300">
              The materials appearing on Smart Reply Pro could include technical, typographical, or photographic errors. Smart Reply Pro does not warrant that any of the materials on its website are accurate, complete, or current. Smart Reply Pro may make changes to the materials contained on its website at any time without notice.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white">7. User Responsibilities</h2>
            <p className="mt-3 text-slate-300">
              You are responsible for:
            </p>
            <ul className="mt-3 space-y-2 text-slate-300">
              <li className="ml-4 list-disc">Maintaining the confidentiality of your account credentials</li>
              <li className="ml-4 list-disc">All activities that occur under your account</li>
              <li className="ml-4 list-disc">Ensuring that content you generate complies with all applicable laws</li>
              <li className="ml-4 list-disc">Not using the service to harass, defame, or threaten others</li>
              <li className="ml-4 list-disc">Reviewing and editing all AI suggestions before sending them anywhere</li>
              <li className="ml-4 list-disc">Understanding that you, not Smart Reply Pro, are the author and sender of any message you compose</li>
            </ul>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white">8. Limitation of Liability</h2>
            <p className="mt-3 text-slate-300">
              Smart Reply Pro shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the service, even if we have been advised of the possibility of such damages.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white">9. Modifications to Service</h2>
            <p className="mt-3 text-slate-300">
              Smart Reply Pro reserves the right to modify or discontinue the service (or any part or content thereof) without notice at any time. We shall not be liable to you or to any third party for any modification, price change, suspension, or discontinuance of the service.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white">10. Termination</h2>
            <p className="mt-3 text-slate-300">
              Smart Reply Pro may terminate or suspend your account and access to the service immediately, without prior notice or liability, if you breach any of these Terms of Use.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white">11. Governing Law</h2>
            <p className="mt-3 text-slate-300">
              These terms and conditions are governed by and construed in accordance with the laws of the jurisdiction in which Smart Reply Pro operates, and you irrevocably submit to the exclusive jurisdiction of the courts in that location.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-white">12. Contact</h2>
            <p className="mt-3 text-slate-300">
              If you have any questions about these Terms of Use, please contact us at:
            </p>
            <p className="mt-3 text-slate-300">
              Email: <a href="mailto:owner@smartreplypro.com" className="text-sky-400 hover:text-sky-300">owner@smartreplypro.com</a>
            </p>
          </div>
        </section>
      </article>
    </main>
  );
}
