export type ReplyGameScenario = {
  id: string;
  category: string;
  intro_line: string;
  incoming_message: string;
  option_a: string;
  option_b: string;
  outcome_a_title: string;
  outcome_a_description: string;
  outcome_b_title: string;
  outcome_b_description: string;
  smartreply_suggestion: string;
  best_choice: "a" | "b";
};

export const replyGameScenarios: ReplyGameScenario[] = [
  {
    id: "dating_01",
    category: "Dating",
    intro_line: "Your phone buzzes.",
    incoming_message: "I thought you said you'd call me yesterday.",
    option_a: "Sorry, I was busy.",
    option_b: "You're right. Yesterday got away from me.",
    outcome_a_title: "Defensive tone detected",
    outcome_a_description: "This reply explains too quickly and can sound dismissive.",
    outcome_b_title: "Tension reduced",
    outcome_b_description: "This reply acknowledges the issue and keeps the conversation calm.",
    smartreply_suggestion: "You're right. Yesterday slipped away from me. I care about this—can we talk today?",
    best_choice: "b",
  },
  {
    id: "work_01",
    category: "Work",
    intro_line: "A Slack notification pops up.",
    incoming_message: "Any update on the deck? Leadership wants it in 15.",
    option_a: "I'm doing like ten things right now.",
    option_b: "Got it. Sending the draft in 10 minutes, then final polish by 15.",
    outcome_a_title: "Pressure escalates",
    outcome_a_description: "The frustration is understandable, but it increases urgency stress.",
    outcome_b_title: "Control established",
    outcome_b_description: "Clear timing and ownership lowers uncertainty.",
    smartreply_suggestion: "On it. Draft in 10 minutes, final version by 15. I'll flag any blockers immediately.",
    best_choice: "b",
  },
  {
    id: "negotiation_01",
    category: "Negotiation",
    intro_line: "A client replies to your proposal.",
    incoming_message: "Your fee is too high. Another team quoted 40% less.",
    option_a: "Then go with them.",
    option_b: "Thanks for sharing that. If budget is key, we can scope phases while keeping outcomes intact.",
    outcome_a_title: "Bridge burned",
    outcome_a_description: "This closes the conversation and signals inflexibility.",
    outcome_b_title: "Leverage retained",
    outcome_b_description: "You acknowledge pressure while reframing around value.",
    smartreply_suggestion: "Appreciate the context. We can phase delivery to fit budget while protecting the core results you need.",
    best_choice: "b",
  },
  {
    id: "conflict_01",
    category: "Conflict",
    intro_line: "A tense text arrives.",
    incoming_message: "You always make this about you.",
    option_a: "That's not true at all.",
    option_b: "I hear you. Can you tell me what felt that way so I can fix it?",
    outcome_a_title: "Argument loop",
    outcome_a_description: "Immediate denial often triggers more accusations.",
    outcome_b_title: "De-escalation",
    outcome_b_description: "You invite specifics and shift toward repair.",
    smartreply_suggestion: "I hear you. I want to understand what landed that way so I can respond better.",
    best_choice: "b",
  },
  {
    id: "friends_01",
    category: "Friends",
    intro_line: "A friend sends a late-night message.",
    incoming_message: "Cool, invite everyone except me next time.",
    option_a: "Wow, dramatic.",
    option_b: "I can see why that felt bad. I should've reached out.",
    outcome_a_title: "Sarcasm spike",
    outcome_a_description: "Mocking tone increases distance.",
    outcome_b_title: "Repair opened",
    outcome_b_description: "Acknowledgment restores trust quickly.",
    smartreply_suggestion: "You're right—that was on me. I should've included you and I'll make it right next time.",
    best_choice: "b",
  },
  {
    id: "family_01",
    category: "Family",
    intro_line: "Message from a parent.",
    incoming_message: "You never call unless you need something.",
    option_a: "That's unfair.",
    option_b: "I get why it feels that way. I want to do better and call this weekend.",
    outcome_a_title: "Defensiveness triggered",
    outcome_a_description: "Calling it unfair can invalidate their feeling.",
    outcome_b_title: "Connection rebuilt",
    outcome_b_description: "Validation plus a concrete step rebuilds consistency.",
    smartreply_suggestion: "I hear you. I haven't been consistent, and that matters. Can we talk this weekend?",
    best_choice: "b",
  },
  {
    id: "boundaries_01",
    category: "Boundaries",
    intro_line: "A coworker pings after hours.",
    incoming_message: "Need you to jump on this tonight.",
    option_a: "Nope, not my problem.",
    option_b: "I can review first thing at 9am. If it's urgent, loop in on-call tonight.",
    outcome_a_title: "Hard stop",
    outcome_a_description: "Boundary is clear, but relationship cost is high.",
    outcome_b_title: "Boundary with structure",
    outcome_b_description: "You protect your time while offering a clear path.",
    smartreply_suggestion: "I’m offline tonight, but I can take this at 9am. For immediate coverage, please route through on-call.",
    best_choice: "b",
  },
  {
    id: "passive_01",
    category: "Passive-aggressive",
    intro_line: "A short text drops in.",
    incoming_message: "No worries. I'll just handle it myself like usual.",
    option_a: "If you want help, ask directly.",
    option_b: "Sounds like you're frustrated. Want to reset and divide this clearly?",
    outcome_a_title: "Friction increases",
    outcome_a_description: "Technically correct, but the tone sounds confrontational.",
    outcome_b_title: "Tension named",
    outcome_b_description: "Naming emotion lowers ambiguity and invites collaboration.",
    smartreply_suggestion: "I hear frustration here. Let's reset and split responsibilities so this feels fair.",
    best_choice: "b",
  },
  {
    id: "work_02",
    category: "Work",
    intro_line: "Your manager comments on your draft.",
    incoming_message: "This isn't what I asked for.",
    option_a: "You weren't clear in the first place.",
    option_b: "Thanks for the flag. Which 2 changes matter most so I can fix fast?",
    outcome_a_title: "Authority clash",
    outcome_a_description: "Blame language creates resistance.",
    outcome_b_title: "Alignment recovered",
    outcome_b_description: "You request focused direction and move to execution.",
    smartreply_suggestion: "Got it—thanks for calling it out. Which two adjustments should I prioritize first?",
    best_choice: "b",
  },
  {
    id: "dating_02",
    category: "Dating",
    intro_line: "You're mid-conversation.",
    incoming_message: "You seem different lately.",
    option_a: "I'm literally the same person.",
    option_b: "I appreciate you saying that. What feels different to you?",
    outcome_a_title: "Invalidation",
    outcome_a_description: "Dismisses their perception and stalls honesty.",
    outcome_b_title: "Curiosity unlocked",
    outcome_b_description: "Invites detail without escalating emotion.",
    smartreply_suggestion: "Thanks for saying that. I want to understand—what's been feeling different lately?",
    best_choice: "b",
  },
  {
    id: "negotiation_02",
    category: "Negotiation",
    intro_line: "A vendor sends terms.",
    incoming_message: "We need a 24-month commitment today.",
    option_a: "Take it or leave it? Fine, we leave.",
    option_b: "We're interested, but 24 months is heavy. Can we do 12 months with a renewal trigger?",
    outcome_a_title: "Deal collapsed",
    outcome_a_description: "You reject without exploring alternatives.",
    outcome_b_title: "Counter-framed",
    outcome_b_description: "You protect flexibility while keeping momentum.",
    smartreply_suggestion: "We're aligned on partnership, but need flexibility. Could we structure 12 months with agreed renewal terms?",
    best_choice: "b",
  },
  {
    id: "conflict_02",
    category: "Conflict",
    intro_line: "A heated thread continues.",
    incoming_message: "Forget it. You don't listen anyway.",
    option_a: "If that's how you feel, whatever.",
    option_b: "I want to listen better. If you're open, tell me the one thing I missed.",
    outcome_a_title: "Shutdown",
    outcome_a_description: "Signals disengagement and confirms their complaint.",
    outcome_b_title: "Re-entry created",
    outcome_b_description: "One-question focus lowers emotional load.",
    smartreply_suggestion: "I don't want this to end there. What's the main point you feel I missed?",
    best_choice: "b",
  },
  {
    id: "friends_02",
    category: "Friends",
    intro_line: "Group chat gets awkward.",
    incoming_message: "Guess some people are too important now.",
    option_a: "Can we not do this in group chat?",
    option_b: "I hear you. I dropped the ball—want to catch up 1:1 tonight?",
    outcome_a_title: "Public tension",
    outcome_a_description: "Boundary is fair, but can feel like avoidance.",
    outcome_b_title: "Private repair path",
    outcome_b_description: "Moves conflict to a safer channel with accountability.",
    smartreply_suggestion: "You're right to call it out. I want to fix it—can we talk 1:1 later today?",
    best_choice: "b",
  },
  {
    id: "family_02",
    category: "Family",
    intro_line: "Sibling texts about plans.",
    incoming_message: "So you're skipping dinner again?",
    option_a: "I have a life too, you know.",
    option_b: "I can't make tonight, but I still want time together—can we lock Sunday?",
    outcome_a_title: "Guilt cycle",
    outcome_a_description: "Escalates family tension with contempt tone.",
    outcome_b_title: "Boundary + care",
    outcome_b_description: "Declines clearly while preserving the relationship.",
    smartreply_suggestion: "I can't tonight, but I do want to see you. Can we plan Sunday and make it happen?",
    best_choice: "b",
  },
  {
    id: "boundaries_02",
    category: "Boundaries",
    intro_line: "An ex reaches out.",
    incoming_message: "Can we talk? Just five minutes.",
    option_a: "Stop texting me.",
    option_b: "I’m not available for this conversation. Wishing you well.",
    outcome_a_title: "Escalation risk",
    outcome_a_description: "Harsh wording may invite further reaction.",
    outcome_b_title: "Clean boundary",
    outcome_b_description: "Firm, brief, and emotionally neutral.",
    smartreply_suggestion: "I’m not open to reconnecting. I wish you the best moving forward.",
    best_choice: "b",
  },
  {
    id: "passive_02",
    category: "Passive-aggressive",
    intro_line: "A teammate responds to your note.",
    incoming_message: "Sure, I'll redo it since my version wasn't good enough.",
    option_a: "That's not what I said.",
    option_b: "I value your work. I asked for changes to match the brief, not to dismiss your effort.",
    outcome_a_title: "Literal defense",
    outcome_a_description: "Accurate, but doesn't address emotion underneath.",
    outcome_b_title: "Respect restored",
    outcome_b_description: "Clarifies intent while affirming contribution.",
    smartreply_suggestion: "Your work matters to me. The edits are about fit for the brief, not about your value.",
    best_choice: "b",
  },
  {
    id: "work_03",
    category: "Work",
    intro_line: "You get called out in email.",
    incoming_message: "Why was I not included on this decision?",
    option_a: "Because we had to move fast.",
    option_b: "Good catch—you should've been looped in. I'll add you now and share context.",
    outcome_a_title: "Exclusion reinforced",
    outcome_a_description: "Explains speed, but doesn't repair trust.",
    outcome_b_title: "Ownership taken",
    outcome_b_description: "A quick acknowledgment diffuses status threat.",
    smartreply_suggestion: "You're right—you should've been included. Adding you now and sending full context in this thread.",
    best_choice: "b",
  },
  {
    id: "negotiation_03",
    category: "Negotiation",
    intro_line: "A recruiter sends final numbers.",
    incoming_message: "This is our best and final offer.",
    option_a: "That's too low. Pass.",
    option_b: "Thanks for sharing. If base can't move, can we discuss signing bonus or 6-month review terms?",
    outcome_a_title: "Options closed",
    outcome_a_description: "You lose leverage by ending too quickly.",
    outcome_b_title: "Value expanded",
    outcome_b_description: "You create negotiable dimensions beyond base pay.",
    smartreply_suggestion: "Appreciate the offer. If base is fixed, could we explore a signing bonus or performance review at month six?",
    best_choice: "b",
  },
  {
    id: "conflict_03",
    category: "Conflict",
    intro_line: "A partner sends a frustrated message.",
    incoming_message: "You ignored me all day.",
    option_a: "I was working, relax.",
    option_b: "I see why that felt bad. I got overloaded and should've sent a quick update.",
    outcome_a_title: "Dismissive impact",
    outcome_a_description: "Minimizes their experience.",
    outcome_b_title: "Accountability shown",
    outcome_b_description: "Owns behavior without overexplaining.",
    smartreply_suggestion: "You're right to flag it. I got overloaded and should've checked in—I'll do better on that.",
    best_choice: "b",
  },
  {
    id: "friends_03",
    category: "Friends",
    intro_line: "A friend asks for money again.",
    incoming_message: "Can you spot me this week? I swear it's the last time.",
    option_a: "You always say that.",
    option_b: "I can't lend right now, but I can help you map a short plan if useful.",
    outcome_a_title: "Judgment spike",
    outcome_a_description: "Calls out pattern but harms rapport.",
    outcome_b_title: "Boundary with support",
    outcome_b_description: "You say no while keeping dignity intact.",
    smartreply_suggestion: "I can’t lend this week. If you want, I can help think through options for getting through the month.",
    best_choice: "b",
  },
  {
    id: "family_03",
    category: "Family",
    intro_line: "A relative comments on your choices.",
    incoming_message: "When are you going to get serious about life?",
    option_a: "You don't know anything about my life.",
    option_b: "I know you mean well. I'm building my path, even if it looks different from yours.",
    outcome_a_title: "Generational clash",
    outcome_a_description: "Valid frustration, but likely escalates.",
    outcome_b_title: "Respectful boundary",
    outcome_b_description: "Maintains self-respect without inviting a fight.",
    smartreply_suggestion: "I know this comes from care. I’m taking my path seriously, even if it looks different.",
    best_choice: "b",
  },
];
